import Head from "next/head";
import Container from "../components/Container";
import Header from "../components/Header";
import axios from "axios";
import { useContext } from "react";
import { AuthContext } from "../context/authContext";
import NotLogged from "../components/NotLogged";
import { signIn, signOut, useSession } from "next-auth/react";
import Loader from "../components/Loader";

const url = "http://localhost:3000/api/todos";

export default function Home({ todos }) {
  // const { isAuth } = useContext(AuthContext);
  const { data: session, status } = useSession();
  console.log(session, status);
  const isLoading = status == "loading";

  return (
    <>
      <Head>
        <title>Todo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading && <Loader />}
      {!isLoading && !session && <NotLogged />}
      {session?.user && <Container todos={todos} />}
      {/* {session?.user ? <Container todos={todos} /> : <NotLogged />} */}
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await axios.get(url);
  return {
    props: {
      todos: data.data,
    },
  };
}
