import Head from "next/head";
import Container from "../components/Container";
import Header from "../components/Header";
import axios from "axios";

const url = "http://localhost:3000/api/todos";

export default function Home({ todos }) {
  return (
    <>
      <Head>
        <title>Todo Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="app_container">
        <Header />
        <main className="min-h-screen">
          <Container todos={todos} />
        </main>
        <footer className="flex flex-row justify-center items-center bg-gray-200 p-2">
          <p className="text-gray-800 text-sm">Harns Technology 2022 - Created By:</p>
          <a href="" target="_blank" rel="noreferrer" className="text-blue-600 ml-2"> sathish kumar</a>
        </footer>
      </div>
    </>
  );
}

export async function getServerSideProps (){
  const { data } = await axios.get(url);
  return {
    props: {
      todos: data.data,
    },
  };
};
